### ISSUE TITLE
GCND

### ISSUE THREAD

**Issue by KCMertens** [instituutnederlandsetaal/gretel#2]
## Bugs:
- [x] zoeken matched resultaten meerdere keren op onlogische manieren. Moet uitgezocht. http://gretel5.ivdnt.loc/xpath-search?currentStep=2&selectedTreebanks=%7B%22gretel%22:%7B%22gcnd_volledig%22:%5B%22alpino%22%5D%7D%7D&retrieveContext=0
- [x] Upload resulteert in rare basex database naam. Geupload als `GCND_volledig` met 1 component `alpino` maar database naam is somehow `GCND_TEST_MAIN_0` Zijn de 2 uploads door elkaar komen te zitten?
- [x] Search is nooit klaar, infinite spinners.
- [x] Ophalen sentence lukt niet. Zelfde probleem met die database naam vermoedelijk.
- [ ] Metadata filter `Lokalisering (<meta type="text" group="Lokalisering" name="Plaats_opname" value="Hofstade"/>)` verschijnt niet in interface. **Metadata met >20 waarden wordt nu geheel verborgen, waarde ophogen kan prima m.i. . Zou anders wellicht een waarschuwing moeten tonen**

## TODO GCND:
- [ ] custom styling van de applicatie. Nog in kaart brengen wat precies @JessedeDoes : overleg met Gent
  Eerste stappen gezet. Nu wachten op feedback.
  - [x] Credits naar about
  - [x] Logo GCND in header
  - [x] Metadata van zinnen direct zichtbaar
  - [x] Kleurtjes
  - [x] Waarschuwing voor dialectzinnen onder example sentence input    
  - [x] Logo's in footer 
- [x] tonen 2 resultaten onder elkaar, zwaar vernederlandste/licht vernederlandste
- [x] Resultaatlijst: koppeling van geluidsfragmenten, link naar volledige transcriptie (in blacklab-applicatie)
- [x] Resultaatlijst: tonen van metadata: docid-regio-plaats (cf. Blacklabinstantie)
- [x] Metadatafilters: wat gebeurt er met properties met veel waarden (zoals plaatsnaam)? checkboxlijst is dan niet zo handig **wordt dropdownlijst** [limiet opgehoogd naar 100]
- [ ] Metadata gaat nu de andere kant op mis. Komen veel meer dan 100 resultaten in te staan
- [ ] export: metadata in export opnemen
  **Dit hebben we toch? Beetje omslachtig, maar het staat als het goed is in de xml**
- [x] overslaan van corpusselectie als er maar 1 corpus is (zou ook algemeen kunnen)
- [x] tooltips zijn te smal (naar Algemeen?)
- [x] Meteen syntax tree tonen bij een resultaatweergave als http://gretel5.ivdnt.loc/xpath-search?currentStep=2&xpath=%2F%2Fmeta%5B@value%3D%22s.107350%22%5D&selectedTreebanks=%7B%22gretel%22:%7B%22gcnd%22:%5B%22alpino%22%5D%7D%7D&retrieveContext=0 (&displayAnalysis=1 ofzo)
  **Voorlopig opgelost door automatisch te tonen wanneer er maar 1 resultaat is**
- [x] upload in GUI uitschakelen
- [x] MWE search uitschakelen (vermoedelijk)
- [ ] [Documentatie pagina](http://gretel5.ivdnt.loc/documentation)  out of date, en niet specifiek voor INT. 
- [ ] About over applicatie bijwerken, About over corpus schrijven (@Gent). De corpusabout zou een lijst voorbeeldsearches met relevante dialectconstructies kunnen bevatten.
- [x] Voor Gent toegankelijke testversie online zetten

## TODO GCND+ (vervolgproject)
- [ ] doorzoeken UD laag (zit nu nog niet in data)
- [ ] example based search voor UD
- [ ] koppelen op GCND-materiaal getrainde parser
- [ ] metadata in analysecomponent?

## TODO ALGEMEEN
- [x] Uploads moeten aan gebruikers gekoppeld zijn
- [ ] Uploads moeten verwijderd kunnen worden
- [ ] Uploads public/niet public werkt niet
- [ ] Admin moet upload kunnen verwijderen (wel zo handig?)
- [x] (nice to have) uploads moeten in celery draaien ipv main thread. Met progress reporting 
- [x] Inloggen
- [x] Django user database
- [ ] OIDC/OAUTH koppeling 

## Nog testen:
- [ ] Upload met tagging vanaf plaintext, chat, folia
- [x] Metadata filtering
